const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const root = path.resolve(__dirname, "..");
const manifest = JSON.parse(fs.readFileSync(path.join(root, "manifest.json"), "utf8"));
const content = fs.readFileSync(path.join(root, "content.js"), "utf8");
const dashboard = fs.readFileSync(path.join(root, "dashboard.js"), "utf8");
const dashboardHtml = fs.readFileSync(path.join(root, "dashboard.html"), "utf8");
const popup = fs.readFileSync(path.join(root, "popup.js"), "utf8");
const background = fs.readFileSync(path.join(root, "background.js"), "utf8");

assert.deepEqual(manifest.content_scripts[0].js, ["filter-utils.js", "content.js"]);
assert.equal(manifest.name, "X FollowTidy");
assert.equal(manifest.icons["128"], "icons/icon-128.png");
for (const size of [16, 32, 48, 128]) {
  assert.equal(fs.existsSync(path.join(root, `icons/icon-${size}.png`)), true, `icon-${size}.png must exist`);
}
assert.equal(content.includes('message.type === "start-unfollow"'), false, "unfiltered start path must not exist");
assert.match(content, /if \(!safeCandidate\(account\)\) return \{ outcome: "safety-check-failed" \};/);
assert.match(content, /if \(!safeCandidate\(account\)\) return \{ outcome: "safety-check-failed" \};[\s\S]*button\.click\(\);[\s\S]*if \(!safeCandidate\(account\)\) return \{ outcome: "safety-check-failed" \};[\s\S]*confirm\.click\(\);/);
const scanPhase = content.match(/async function scanPhase\(\) \{([\s\S]*?)\n\}/)?.[1] || "";
assert.match(scanPhase, /run\.candidates\.set\(key, next\);[\s\S]*processVisibleCandidate\(\{ waitUntilDue: true \}\)/, "an eligible account must be consumed before scanning moves on");
assert.doesNotMatch(scanPhase, /processVisibleCandidate\(\{ waitUntilDue: false \}\)/, "scanning must not leave eligible accounts behind in X's virtualized list");
assert.match(content, /run\.nextActionAt = Date\.now\(\) \+ waitMilliseconds;/, "unfollow pacing must use a non-blocking deadline");
assert.doesNotMatch(content, /await applyPacing\(\)/, "pacing must not block the scan loop");
assert.match(content, /run\.processed\.delete\(key\);[\s\S]*run\.stopRequested = true;[\s\S]*run\.pauseKind = outcome;/, "a rejected X action must remain queued and auto-pause");
assert.match(content, /if \(!cell \|\| !unfollowButtonFor\(account\.handle\)\)/, "an unfollow must be verified from the resulting Following state");
assert.match(content, /looksLikeRateLimit\(newAlert\)/, "X rate-limit alerts must be checked after confirmation");
assert.match(content, /advanceFollowingList\(\);[\s\S]*lastNewAccountAt >= 90_000/, "the scan must keep advancing the virtual list before declaring it stalled");
assert.doesNotMatch(content, /position\.atEnd && Date\.now\(\) - lastNewAccountAt >= 30_000\) break/, "a temporary virtual-list bottom must never be treated as Finished");
assert.match(content, /run\.checked >= run\.expectedFollowing/, "Finished must require the exact Following total when X exposes it");
assert.match(content, /exactFollowingCountFromPage/, "the scanner must read the account's own exact Following total");
assert.match(content, /resolveExpectedFollowingCount[\s\S]*dispatchHover\(profileLink\)/, "the scanner must obtain the exact total from the list owner's hover card when needed");
assert.match(content, /function dispatchHover\(element\)/, "every startup hover call must use the defined hover helper");
assert.doesNotMatch(content, /dispatchPointerSequence/, "undefined legacy hover helpers must not be called");
assert.match(content, /let finalMessage = "";[\s\S]*try \{[\s\S]*resolveExpectedFollowingCount\(\)/, "startup discovery failures must be caught and reported instead of leaving the dashboard stuck");
assert.match(content, /function followingScrollTarget\(\)/, "the scanner must discover X's actual scroll container");
assert.match(content, /remainingLoaded <= 2/, "the scanner must advance before exhausting the rendered batch");
assert.match(content, /scrolled \$\{Math\.round\(moved\)\}px/, "scroll movement must be measured and reported");
assert.match(content, /run\.pauseKind = "scan-stalled"/, "a stalled virtual list must pause instead of being marked complete");
assert.match(dashboard, /const PAGE_SIZE = 10;/);
assert.match(dashboard, /status\.scannedUsers \|\| \[\]/);
assert.match(content, /waitingUntil: run\.nextActionAt/, "the worker must publish an absolute pacing deadline");
assert.match(dashboard, /deadline - Date\.now\(\)/, "the dashboard must recalculate the countdown from the current time");
assert.match(content, /run\.unfollowed > 0 && run\.unfollowed % run\.settings\.batchSize === 0/, "batch cooldowns must count successful unfollows only");
assert.match(dashboard, /status\.queued \|\| 0\} waiting/, "the dashboard must keep the bounded waiting candidate visible");
assert.match(dashboardHtml, /id="limit-notice"/, "the dashboard must show an automatic-pause warning");
assert.match(dashboardHtml, /https:\/\/github\.com\/sponsors\/0xAllenChen/, "the optional sponsor card must link to the requested GitHub Sponsors page");
assert.match(dashboardHtml, /id="donation-later"/, "the donation prompt must be dismissible");
assert.match(dashboard, /donationDismissed \|\| !status\.running/, "the donation prompt must remain non-blocking and appear only after startup");
assert.doesNotMatch(popup, /chrome\.tabs\.create\(\{ url: tab\.url/, "starting must not duplicate the X Following tab");
assert.match(manifest.permissions.join(","), /sidePanel/, "the dashboard must use Chrome's native side panel");
assert.equal(manifest.side_panel, undefined, "the dashboard must not be registered as a global side panel");
assert.match(popup, /chrome\.sidePanel\.setOptions\(\{ tabId: tab\.id, path: "dashboard\.html", enabled: true \}\)/, "the panel must be enabled only for the selected Following tab");
assert.match(popup, /chrome\.sidePanel\.open\(\{ tabId: tab\.id \}\)/, "Start must open the dashboard beside X");
assert.match(popup, /const launch = chrome\.runtime\.sendMessage\(\{[\s\S]*type: "launch-run"/, "the background launch must begin before opening the side panel closes the popup");
assert.match(popup, /url: "about:blank"[\s\S]*type: "prepare-run"[\s\S]*navigateToFollowing: needsFollowingPage/, "Start must prepare an inactive tab before background navigation");
assert.match(background, /chrome\.tabs\.update\(message\.tabId, \{ url: "https:\/\/x\.com\/following" \}\)/, "the background must navigate users to their Following page");
assert.match(background, /waitForFollowingTab\(message\.tabId\)/, "the background must wait for X's user-specific Following route before injection");
assert.match(background, /message\.type === "launch-run"/, "the service worker must own the complete launch sequence");
assert.match(background, /type: "start-filtered-unfollow"/, "the service worker must start the page worker after injection");
assert.doesNotMatch(popup, /place-worker-window/, "starting must not move or regroup tabs");
assert.doesNotMatch(background, /chrome\.tabs\.group|chrome\.windows\.create/, "the extension must not move the user into a work window or tab group");
assert.match(background, /chrome\.tabs\.onRemoved\.addListener/, "closing the X work tab must be detected");
assert.match(background, /pauseKind: "worker-closed"/, "a closed X work tab must terminate the run with a visible reason");
assert.doesNotMatch(content, /while \(document\.hidden/, "an unfocused work window must not be mistaken for a paused or minimized page");
assert.doesNotMatch(dashboard, /RESTORE X WINDOW/, "the dashboard must not show a false visibility pause");
assert.match(content, /advanceFollowingListAndWait/, "virtual-list scrolling must continue without focus switching");
assert.doesNotMatch(content, /focus-work-window|restore-previous-window|chrome\.tabs\.update/, "the worker must never request tab switching");
assert.match(background, /chrome\.tabs\.onUpdated\.addListener[\s\S]*runStatus\?\.tabId === tabId[\s\S]*runStatus\?\.streaming === true/, "the panel must remain bound only to the active run's Following tab");

console.log("safety structure tests passed");
